### ISSUE TITLE
some exception in aggregation 

### ISSUE THREAD

**Issue by mrz8** [SecTeamPolaris/ProGraph#1]
Describe the bug
I ran all the cells but I got this  error :

[<ipython-input-55-1192fba9dd07>](https://localhost:8080/#) in <cell line: 22>()
     22 for e in range(epoch):
     23     # nodes aggregate info from neighbours and update the adjoin edges
---> 24     adj_matrix = aggregation(clts_adj,adj_matrix,labels)
     25     # update the labels
     26 #     labels = label_update(clts_adj,labels)

[<ipython-input-54-d3cd7ce91876>](https://localhost:8080/#) in spread(clts, adj_matrix, labels, th, mode)
     19             if labels[j] == -1: #ignore the unlabel testing nodes
     20                 continue
---> 21             score_list[labels[j]] += adj_matrix[i][j]
     22         if np.array(score_list).sum() == 0:
     23             continue

IndexError: list index out of range

ه

**Comment by SecTeamPolaris** [comment]
We re-upload ProGraph.ipynb. Maybe it helps to solve the issue. You can try again. Thanks.

**Comment by mrz8** [comment]
the new code does not have the novelty detection part anymore :(
